name: Build Android APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Cache Buildozer global directory
        uses: actions/cache@v3
        with:
          path: ~/.buildozer
          key: buildozer-global-${{ runner.os }}-${{ hashFiles('buildozer.spec') }}
          restore-keys: |
            buildozer-global-${{ runner.os }}-

      - name: Cache Buildozer project directory
        uses: actions/cache@v3
        with:
          path: .buildozer
          key: buildozer-project-${{ runner.os }}-${{ hashFiles('buildozer.spec') }}
          restore-keys: |
            buildozer-project-${{ runner.os }}-

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y build-essential git zip unzip openjdk-17-jdk python3-pip autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev libtinfo5 cmake libffi-dev libssl-dev libltdl-dev
          pip install --upgrade pip
          pip install "cython<3.0.0"
          pip install --upgrade buildozer virtualenv

      - name: Build with Buildozer
        run: |
          buildozer android debug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v3
        with:
          name: ShopZone-APK
          path: bin/*.apk
